version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: notes-app-db
    environment:
      POSTGRES_DB: notes_app
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional: for initial setup
    restart: unless-stopped
